import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const kanit = Kanit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Custodian",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kanit.className} gradient-bg`}>
        <Navbar />
        <main>{children}</main>
        <footer className="text-gray-600 body-font">
          <div className="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
            <a
              href="/"
              className="flex title-font font-medium items-center text-green-500 mb-4 md:mb-0"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="none"
                stroke="currentColor"
                strokeWidth="0.5"
                className="bi bi-triangle"
                viewBox="0 0 16 16"
              >
                <path d="M8 1L15 14H1L8 1Z" />
                <path d="M8 2L13.5 13H2.5L8 2Z" />
                <path d="M8 3L12 12H4L8 3Z" />
                <path d="M8 4L10.5 11H5.5L8 4Z" />
                <path d="M8 5L9 10H7L8 5Z" />
              </svg>
              <span className="ml-3 text-xl">CUSTODIAN</span>
            </a>
            <p className="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
              © 2022 Custodian —
              <a
                href="https://www.facebook.com/photo/?fbid=1017449392701114&set=ecnf.100033081885229"
                className="text-green-500 ml-1"
                rel="noopener noreferrer"
                target="_blank"
              >
                @komari
              </a>
            </p>
            <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
              {/* Add social icons or additional links here */}
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
